# File: .github/workflows/ci.yml
#
# GitHub Actions CI for CLibs.
# * Builds on Ubuntu & macOS
# * Tests with both GCC and Clang.
# * Enables sanitizers on Debug builds.
# * Runs CTest to execute all registered tests.

name: Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build-and-test:
    name: Build & Test on ${{ matrix.os }} / ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        compiler: [ gcc, clang ]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install cmake
          if [ "${{ matrix.compiler }}" == "gcc" ]; then
            sudo apt-get install -y build-essential
          else
            sudo apt-get install -y clang
          fi
          sudo apt-get install -y valgrind

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake gcc

      - name: Configure CMake
        shell: bash
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        shell: bash
        run: cmake --build build -- -j$(nproc)

      - name: Run unit tests
        shell: bash
        run: |
          cd build
          ctest --output-on-failure

      - name: Check memory leaks (macOS)
        shell: bash
        if: runner.os == 'macOS'
        run: |
          cd build
          leaks -quiet --atExit -- ./tests

      - name: Check memory leaks (Linux)
        shell: bash
        if: runner.os == 'Linux'
        run: |
          cd build
          valgrind --leak-check=full --show-reachable=yes --track-origins=yes ./tests
